version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - selenium

    selenium:
        image: selenium/standalone-chrome-debug:3.7.1
        ports:
            - 4444:4444   # Selenium
            - 5900:5900   # VNC server
